Fix 'let name of names' -> 'let name in names' typos
Avoid:

  >> error: couldn't process source due to parse error
  >> Line ...: Unexpected identifier

when packaging this library with ngAnnotate:dist.  The standard syntax
for iterating over an object is (since ECMAScript 5.1 [1]):

  for (variable in object) {
    ...
  }

I haven't been able to turn up any docs on 'for (variable on object)'.

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in